# https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: at.crd.k8s.d7kj.com
spec:
  group: crd.k8s.d7kj.com
  names:
    kind: At
    listKind: AtList
    plural: at
  scope: Namespaced
  # version: v1
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
      served: true
      storage: true
