---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: operator-test
  name: operator-test
  namespace: testing
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: operator-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: operator-test
    spec:
      containers:
      - name: operator-test
        image: registry.cn-shenzhen.aliyuncs.com/longmon/k8s-operator-test:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: k8s-test-operator
      serviceAccountName: k8s-test-operator
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: operator-test
  namespace: testing
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: operator-test
spec:
  externalTrafficPolicy: Cluster
  selector:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: operator-test
  ports:
  - port: 9876
    targetPort: 9876
  type: NodePort
