kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-cluster-demo # 集群名称
nodes:
  - role: control-plane # 控制平面节点
    # image: kindest/node:v1.32.2 # 节点镜像
  - role: worker # 工作节点
    # image: kindest/node:v1.32.2 # 节点镜像
