
# 应用于全部分组
all:
  vars:
    # 在宿主机执行
    # cp ~/.vagrant.d/insecure_private_key .
    ansible_ssh_private_key_file: /home/vagrant/insecure_private_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
# ansible k8s -i inventory.yaml -m ping
masters:
  vars:
  hosts:
    master:
      ansible_host: 192.168.56.10

nodes:
  vars:
  hosts:
    node1:
      ansible_host: 192.168.56.11

k8s:
  children:
    masters:
    nodes:
