
# ansible k8s -i inventory.yaml -m ping
k8s:
  hosts:
    master:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
    node1:
      ansible_host: 192.168.56.11
      ansible_user: vagrant
