# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # 启用链接克隆以节省磁盘空间和创建时间
  # 会先创建一个 base 虚拟机，然后 config.vm.define 都复制这个虚拟机，加速了安装过程
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessable to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  master_ip = "192.168.33.10"
  
  # 指定当前 K8s 集群中 Service 所使用的 CIDR
  SERVICE_CIDR="10.96.0.0/12"

  # 指定当前 K8s 集群中 Pod 所使用的 CIDR
  POD_CIDR="10.244.0.0/16"
  master_name = "k8s-master"
  config.vm.define master_name do |master|
    hostname = master_name
    master.vm.hostname = hostname
    # host-only 模式
	  master.vm.network "private_network", ip: master_ip
	  master.vm.provider "virtualbox" do |vb|
	    vb.name = hostname
	    vb.memory = 2048
	    vb.cpus = 2
	  end
	  master.vm.provision "shell", path: "scripts/common.sh", env: {"MASTER_IP"=>master_ip, "SERVICE_CIDR"=>SERVICE_CIDR, "POD_CIDR"=>POD_CIDR}
	  master.vm.provision "shell", path: "scripts/master.sh", env: {"MASTER_IP"=>master_ip, "SERVICE_CIDR"=>SERVICE_CIDR, "POD_CIDR"=>POD_CIDR}
  end
  
  (1..1).each do |i|
    config.vm.define "k8s-worker#{i}" do |worker|
      # worker.vm.clone = master_name # 克隆主节点的配置
      hostname = "k8s-worker#{i}"
      worker.vm.hostname = hostname
      worker.vm.network "private_network", ip: "192.168.33.1#{i}"
      worker.vm.provider "virtualbox" do |vb|
        vb.name = hostname
        # vb.memory = 2048
        # vb.cpus = 2
      end
      worker.vm.provision "shell", path: "scripts/common.sh"
      worker.vm.provision "shell", path: "scripts/worker.sh"
    end
  end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # 定义主机映射
  hosts_entries = [
    "192.168.33.10 k8s-master",
    "192.168.33.11 k8s-worker1",
    "192.168.33.12 k8s-worker2"
  ]
  # provision 模块指的是在Vagrant完成虚拟开发环境的创建后，让虚拟机自动执行的自定义脚本。
  config.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
      # 设置主机名
    #echo "设置主机名: $1"
    #hostnamectl set-hostname $1
    echo "全部运行的shell"
    # 确保只添加一次
    for entry in "#{hosts_entries.join('" "')}"; do
      #echo "遍历项: $entry"
      if ! grep -qF "$entry" /etc/hosts; then
        echo "添加: $entry"
        echo "$entry" | tee -a /etc/hosts
      else
        echo "已存在: $entry"
      fi
    done
  SHELL
end
