
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pc-cronjob
  namespace: dev
spec:
  # 每分钟执行一次
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 5
      parallelism: 2
      
      template:
        metadata:
          name: pc-cronjob
          labels:
            app: pc-cronjob
        spec:
          containers:
          - name: counter
            image: busybox
            command: ["sh", "-c", "for i in 5 4 3 2 1; do echo $i; sleep 20; done"]
          restartPolicy: Never
