
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev
type: Opaque
data:
  db-username: YWRtaW4=      # base64 编码的 "admin"
  db-password: MTIzNDU2    # base64
  db-name: bXlkYg==        # base64 编码的 "mydb"
  